'roi_heads.box_predictor.cls_score.weight' has shape (81, 1024) in the checkpoint but (12, 1024) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (81,) in the checkpoint but (12,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (320, 1024) in the checkpoint but (44, 1024) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (320,) in the checkpoint but (44,) in the model! Skipped.
'proposal_generator.anchor_generator.cell_anchors.0' has shape (3, 4) in the checkpoint but (15, 4) in the model! Skipped.
'proposal_generator.rpn_head.conv.weight' has shape (256, 256, 3, 3) in the checkpoint but (1024, 1024, 3, 3) in the model! Skipped.
'proposal_generator.rpn_head.conv.bias' has shape (256,) in the checkpoint but (1024,) in the model! Skipped.
'proposal_generator.rpn_head.objectness_logits.weight' has shape (3, 256, 1, 1) in the checkpoint but (15, 1024, 1, 1) in the model! Skipped.
'proposal_generator.rpn_head.objectness_logits.bias' has shape (3,) in the checkpoint but (15,) in the model! Skipped.
'proposal_generator.rpn_head.anchor_deltas.weight' has shape (12, 256, 1, 1) in the checkpoint but (60, 1024, 1, 1) in the model! Skipped.
'proposal_generator.rpn_head.anchor_deltas.bias' has shape (12,) in the checkpoint but (60,) in the model! Skipped.
'roi_heads.box_predictor.cls_score.weight' has shape (12, 1024) in the checkpoint but (81, 2048) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (12,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (44, 1024) in the checkpoint but (320, 2048) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (44,) in the checkpoint but (320,) in the model! Skipped.
Traceback (most recent call last):
  File "infer.py", line 32, in <module>
    DatasetCatalog.register("nusc_" + d, lambda d=d: get_dicts("./"))
  File "/home/pmallya/anaconda3/envs/det2/lib/python3.6/site-packages/detectron2/data/catalog.py", line 39, in register
    name
AssertionError: Dataset 'nusc_train' is already registered!
