Traceback (most recent call last):
  File "infer.py", line 132, in <module>
    ground['img_id'] = d["sample_data_token"]
KeyError: 'sample_data_token'
